server:
  port: 8080

spring:
  application:
    name: user-management-application
  datasource:
    url: jdbc:h2:file:./database/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


logging:
  level:
    root: error
    web: error
    org:
      springframework: info
    es:
      ibm: debug
